### ISSUE TITLE
v 0.7 epic

### ISSUE THREAD

**Issue by dyoder** [dashkite/dashkite.com#5]
- [ ] Initial sitemap
- [ ] Static/edge rendering problems
  - [x] We're only rendering /
  - [ ] Cheerio (?) is double-escaping HTML
- [x] More … page nav should be an expanded menu, not a list
- [ ] Permalinks don't seem to work
  - [ ] Add link indicator?
- [x] Incorporate new focus style for links
- [ ] Content
  - [x] Copyediting
    - [x] About Us
      - [x] Could be less stilted
      - [x] Need more for Eliset and Adele
        - [ ] Get permission to include them
      - [x] Add photos
  - [x] Our Mission
    - [x] Expand, include links to more details
- [ ] New content
  - [ ] Privacy and Security
  - [ ] Safety
- [ ] Content components (Vellum)
  - [ ] Card
  - [ ] Article summary
  - [x] Nav menu
  - [ ] Social badges
  - [ ] Social card?
- [ ] Open problems
  - [ ] Adapt to device margins so bottom nav isn't hidden
  - [x] Theming Vellum components
  - [ ] When to reboot Hydrogen
    - [ ] Separate indexer (enables data binding/wiki-links/search) into separate module?
      - [ ] Relationship to sitemap? Edge-rendered sitemap?
  - [ ] Best way to incorporate images into articles?
    - [ ] Nested Vellum components? ex Image? Figure?
