### ISSUE TITLE
Version 0.9 Epic

### ISSUE THREAD

**Issue by dyoder** [dashkite/dashkite.com#6]
- [ ] Product logos should link
  - [ ] To product detail from product overview page
  - [ ] To the actual product from the product detail page
- [ ] Change disinformation link to [Obama interview (excerpt?)][vox]
- [ ] Add innovations page after we add 2-3 more innovation articles
  - [ ] Graph database on top of DynamoDB
  - [ ] [Other candidates][wiki]
- [ ] #30
- [ ] Cheerio (?) is double-escaping HTML
- [ ] Permalinks don't seem to work
  - [ ] Add link indicator?
- [ ] Content
- [ ] New content
  - [ ] Privacy and Security
  - [ ] Safety
- [ ] Content components (Vellum)
  - [ ] Card
  - [ ] Article summary
  - [ ] Social badges
  - [ ] Social card?
- [ ] Open problems
  - [ ] Adapt to device margins so bottom nav isn't hidden
  - [ ] When to reboot Hydrogen
    - [ ] Separate indexer (enables data binding/wiki-links/search) into separate module?
      - [ ] Relationship to sitemap? Edge-rendered sitemap?
  - [ ] Best way to incorporate images into articles?
    - [ ] Nested Vellum components? ex Image? Figure?
- [ ] Possibly add CA notice to privacy policy? Ex: [Grammarly][gr]

[vox]: https://www.vox.com/recode/2020/11/16/21570072/obama-internet-threat-democracy-facebook-fox-atlantic
[wiki]: https://github.com/dashkite/wiki/blob/b779cddc20bcb555613f758c782af3437071a3d5/innovations.md
[gr]: https://www.grammarly.com/privacy-policy#for-california-users

**Comment by dyoder** [comment]
Obsolete
